---
all:
  hosts:
    dev-srv01:
      ansible_host: dev-srv
      ansible_os_family: Debian
      ansible_become_pass: "{{ vault_dev_pass }}"
    dev-local:
      ansible_host: demo-srv
      ansible_os_family: Debian
      ansible_user: root
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    deb_srv:
      hosts:
        dev-srv01:
        dev-local: